# version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend
    restart: always
    env_file: .env
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/views:/usr/src/frontend/views:ro
      - ./frontend/public:/usr/src/frontend/public:ro
    depends_on:
      - db
    networks:
      - my-network
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: my-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      # Montar vistas
      - ./frontend/views:/usr/share/nginx/html/views:ro
      # Montar archivos estáticos
      - ./frontend/public/css:/usr/share/nginx/html/css:ro
      - ./frontend/public/img:/usr/share/nginx/html/img:ro
      - ./frontend/public/index.html:/usr/share/nginx/html/index.html:ro
      - ./frontend/public/matricula_web.html:/usr/share/nginx/html/matricula_web.html:ro
      # Montar solo la carpeta API
      - ./frontend/js/api:/usr/share/nginx/html/js/api:ro
      # Montar archivos JS individuales de public/js
      - ./frontend/public/js/auth.js:/usr/share/nginx/html/js/auth.js:ro
      - ./frontend/public/js/config.js:/usr/share/nginx/html/js/config.js:ro
      - ./frontend/public/js/matriculaWeb.js:/usr/share/nginx/html/js/matriculaWeb.js:ro
      # Configuración nginx
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: my-db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Lima
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3300:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge